# 버전 지정
version: "3.7"

# 컨테이너 설정
services:
  database:
    # Docker Container Name
    container_name: Saju-Database
    # Image to use
    image: mysql
    # 컨테이너 다운 시 재시작하라는 명령어
    restart: always
    # 데이터베이스 컨테이너 안의 환경변수 설정
    environment:
      # 기본적으로 생성할 DB
      - MYSQL_DATABASE=saju
      # 기본 Root 계정의 비밀번호
      - MYSQL_ROOT_PASSWORD=wjdwhdans
      # 데이터베이스 타임존
      - TZ=Asia/Seoul
    # Port 지정
    ports:
      - "33000:33000"